### ISSUE TITLE
開発予定メモが欲しい

### ISSUE THREAD

**Issue by la-png** [PUJP/Tourcord#2]
リポジトリ内に、予定している機能、完成済みの機能、余裕が出たら入れたい機能のメモを作って欲しい

**Comment by la-png** [comment]
てすてす

**Comment by Allianaab2m** [comment]
Projects機能を使ってみました。
ToDo -> issues,PRがオープンされたときに追加
In Progress -> issues,PRが再オープンされたときに追加
Done -> issuesのクローズ，PRマージで追加
としています。

**Comment by Allianaab2m** [comment]
手動で移動させることもできそうです。

**Comment by la-png** [comment]
おー、便利ですね。
ただ、全体像をざっくり把握したくて、txtなりmdなり、フロー図表でもいいですが、全体の概要を書いたファイルが欲しかったんです。

機能個別の詳細を見るためにはこれも便利そうなので、併用したいと思うのですが、どうでしょうか？

**Comment by Allianaab2m** [comment]
私も着手し始めてフロー図表欲しいなーと思っていたところなのでぼちぼちdrawio使って描いてます。

issuesはPyCharmと連携してチケット駆動開発できるので，issuesでタスク管理していきましょうか。

**Comment by la-png** [comment]
LGTM
